### ISSUE TITLE
Project failed to init

### ISSUE THREAD

**Issue by kuccilim** [SuTV/react-native-base-project#3]
Project were failed to init due to plugin "react-native-facebook-login" require native side configurations.

**Comment by SuTV** [comment]
Thanks @kuccilim for reporting. For Android build, you should change:
`com.facebook.android:facebook-android-sdk:4+`
to
`com.facebook.android:facebook-android-sdk:4.26.0`
in file **node_modules/react-native-fbsdk/android/build.gradle** due to [this issue](https://stackoverflow.com/questions/47671206/getting-error-when-run-react-native-run-android)
And please replace YOUR_FACEBOOK_APP_ID in file strings.xml by your own Facebook app id to use Facebook login function
